application: spimemanger
version: 1
runtime: python
api_version: 1

handlers:
- url: /styles
  static_dir: styles

- url: /js
  static_dir: js 

- url: /media
  static_dir: media
  
- url: /test.*
  script: gaeunit.py
    
- url: .*
  script: hub.py